#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #

import rospy
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist

class Obstacle():
    def __init__(self):
        self.LIDAR_ERR = 0.05
        self.LIDAR_MAX = 2
        self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        # print 1
        self.obstacle()

    def obstacle(self):
        self.twist = Twist()
        while not rospy.is_shutdown():
            msg = rospy.wait_for_message("scan", LaserScan)
            # print 2
            # self.scan_filter = []
            min_ang=0
            min_dis=10
            for i in range(360):
                if i <= 45 or i > 315:
                    if msg.ranges[i] >= self.LIDAR_ERR and msg.ranges[i]<=self.LIDAR_MAX:
                    	if msg.ranges[i] < min_dis:
                    		min_dis = msg.ranges[i]
                    		min_ang = i
                        # self.scan_filter.append(msg.ranges[i])
            if min_dis < 0.3:
                self.twist.linear.x = 0.0
                self.twist.angular.z = 0.0
                self._cmd_pub.publish(self.twist)
                rospy.loginfo('Stop!')

            else:
                self.twist.linear.x = 0.0
                self.twist.angular.z = 0.0
                rospy.loginfo('distance of the obstacle : %f', min_dis)
                rospy.loginfo('angular of the obstacle : %f', min_ang)

            self._cmd_pub.publish(self.twist)

def main():
    rospy.init_node('turtlebot3_obstacle')
    try:
        obstacle = Obstacle()
    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()
